# Generated by Django 6.0.7 on 2026-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
